const gameLinks = [
  {
    superMethaneBros:
      "https://mega.nz/file/mh5gmQpJ#tadL2EG05MVTgVLIlb62rT8ia05ZV5sVMchn_-Cevx8",
  },
  {
    asteroidz3d:
      "https://mega.nz/file/f5YwkTrC#C9tmlwKGryRxEQjHcP6fJjWG4XQ7gPxpM83eVZmYM0g",
  },
  {
    threeSixty:
      "https://mega.nz/file/2tw2wYZQ#xuMkGcBC4qyQd1oX4fYacFiZfoBmH4szy0ExQ588HjI",
  },
  {
    threeDeeRacing:
      "https://mega.nz/file/bhgHSC5D#u4Az5UBQ7JqPLqGD8HnvzzR0tQEH-Q2luwGyWK2UdoQ",
  },
  {
    abaDaba:
      "https://mega.nz/file/q1ZCgJYB#EeFzwVunmy2z3iYr8007RmSIdcdhNyCEH-ep6THa1Z0",
  },
  {
    codex:
      "https://mega.nz/file/GkQQWJLJ#pTUnEzgokH2O0m3mGk9zIfCnK2WjcubiSkw2iO673wk",
  },
  {
    tetrisBreak:
      "https://mega.nz/file/69YSyZyR#RXS8-pUTsd8UcMXYwLP66P3_SlNPndsOlNQPcR_4XTc",
  },
  {
    yambo:
      "https://mega.nz/file/O5Jy1ZDJ#iDFgaWXrPuAMbUbXJabzvROxvDP6DseAgdmphc5yl2Q",
  },
  {
    powerShooter:
      "https://mega.nz/file/3hQCVDTL#vAFMzfLQcUYZLOZrg8oAshomD36G8cqpDvp4lat6LEw",
  },
  {
    houseOfUsher:
      "https://mega.nz/file/e0pWkApD#7iysW-fgMSWX1ThVnzeVMwYP-4EMhbSLc4dIq1hxCzA",
  },
  {
    ufo: "https://mega.nz/file/igJ22DAB#ou8DDd6R6KK35Ei7yjZh1Ci3OlYRTT6mwxjmL26Sny0",
  },
  {
    marioXp:
      "https://mega.nz/file/CtZUVL5R#mP7fvcFG5Hucvu8ZJ2z3aepfh_CNS8TCcCjf9sEELmc",
  },
  {
    madnessInteractive:
      "https://mega.nz/file/2tBQwD5a#UOgaenlmY6c4Ejou8IBgb4JhZNOT8mC3msl_5Gwr8T8",
  },
  {
    alex: "https://mega.nz/file/WxIWWTRY#Y9LC4MrTCqeNMXK-uRcQeD7EAAio1azmuJeku2jRRcA",
  },
  {
    absoluteMastermind:
      "https://mega.nz/file/G5J0kZII#gP43BBZpkNBjEJi9Y-GwUb2evVkFhSQZ2cnGr3Vdua8",
  },
  {
    atoll:
      "https://mega.nz/file/OsIBiaqA#i-LDye_fWrtn2dPdUrkwDFReaCoEgkvmQ_jq07sa0bA",
  },
  {
    atris:
      "https://mega.nz/file/uspExIib#BMi2FqS4rBTr-C_6YmbzTG8wsJV6MD6oTd5qqIEAx2Y",
  },
  {
    bricks:
      "https://mega.nz/file/mtI22ZoS#D4b1cRC5COZwbFGxPlaPR5dMwNrFaW0QDEr6V7vNXkU",
  },
  {
    blackJack:
      "https://mega.nz/file/eoxwUJbD#scvMhDndtpYyUsTHjJmYVIflrKu5tGK1rywCPVdnPuo",
  },
  {
    blocks:
      "https://mega.nz/file/LtpgyYrY#3AX8906jNw8wOcaBvCXd6bLyTj2a_4dPWYyTs3qOlPw",
  },
  {
    camyTwo:
      "https://mega.nz/file/qtp00I7Z#ZCSePpM4dFIJly9TxHX6GvImSe6MTOROVyAGtFKpkUE",
  },
  {
    capman:
      "https://mega.nz/file/fgpWla6L#gCQmzA7XdHmzjrWw-ljCaA9r3p7uSOTNRprp9yL8WNI",
  },
  {
    chickenInvaders:
      "https://mega.nz/file/KkwAmATZ#ZBfoPDzA2HC0CR_YXOqOwCZGBUz9UPNv80sWvp1FHKE",
  },
  {
    colorMagic:
      "https://mega.nz/file/bsh20bJb#yxwadIct7gPA4MN_JmF-CHVXb7ocEidUDsf4owsLZOk",
  },
  {
    cyberMind:
      "https://mega.nz/file/i1B3jAYI#FwZs4nBTbZkedcQGayjebTb2OuMVRZO0ZiLilh6Sc5Y",
  },
  {
    cobjacks:
      "https://mega.nz/file/X9hSDDKR#3y4JBm9cj21UUwx1C8R66e1ZOhmE4HqnRMSl5xaVDuo",
  },
  {
    crystalStacker:
      "https://mega.nz/file/f5IgGbBJ#ziazr1fnP-7fhVGIIoiELL9RosvkIyUNhBmwgwl9vk0",
  },
  {
    dolphinDice:
      "https://mega.nz/file/ewA2ARTL#HrHt1wqFxooDVb2y140RNcFQqA4znVtxUg-udj7cHuQ",
  },
  {
    depthDiver:
      "https://mega.nz/file/yxRigbDb#sPHHGueBtUpasg3s9qWomlGrFDiPWVYtmLuyQE2aDlc",
  },
  {
    deluxePacman:
      "https://mega.nz/file/bgISFJrb#MHotUnh0fFvchYaAZ5tGS7QOnekP-JuQ4mWUK8MWfxE",
  },
  {
    drHorst:
      "https://mega.nz/file/XoAEVTrQ#fYK0i1-0_xm24EjHao2CmyE05-rcBUrI5D_iS6p9phA",
  },
  {
    dropsOfLight:
      "https://mega.nz/file/r0ZSRbaT#Ik9_f3Dh6TIj_CYCIdl7dRnIwhpumge8StARLTjzNkY",
  },
  {
    lordMonarchOnline:
      "https://mega.nz/file/7hAmzBgC#71J3cfL08qCj820swd7wNuXXOt5uhmC-X5tiBFpjlXI",
  },
  {
    darkWars:
      "https://mega.nz/file/KlBzWKTK#ycjXcX88XYUZM8cFC-JK1q-RGPXqt_X7lvMUnHvMIwg",
  },
  {
    dxBall:
      "https://mega.nz/file/HkowTLgR#9Vei5dQJkIz54P257ERUQMo1KsuaohwXc7NyGJvl1Jc",
  },
  {
    driftZone:
      "https://mega.nz/file/W9ZjjAqY#-WQTafSPdE0W79vkBdTOyY76ZI0JOT0wZgBmTrPoPI4",
  },
  {
    egoboo:
      "https://mega.nz/file/zt53zCQT#Uoe839kofnDRG6a2RBRaFktxEDW2AhazewnVVRiCSQQ",
  },
  {
    eyDice:
      "https://mega.nz/file/jp4hAQIb#7AFI9xEfYU7egRnKagx5yD5_5uKJnsXcmkii-ray1Z4",
  },
  {
    factorX:
      "https://mega.nz/file/OlIRyQxa#c7autTIcPSzEkIPVkzWcHFC-4g9_4Y-3WzU7T0cU5p8",
  },
  {
    frozenBubble:
      "https://mega.nz/file/m5Bl2YiZ#NebJ31fuoSN82hYQngZdziiqB0rd88evO3dgGButnOY",
  },
  {
    frendz:
      "https://mega.nz/file/ulAWBbLB#10c2FTvVUJPmjLQBu8aDk6GYHC503tF9LGF5icAiZfs",
  },
  {
    general:
      "https://mega.nz/file/jthT0IKY#FC8G2cvNkODkAi6EnAYkT7GySFIup15_Iiav1ivB3UI",
  },
  {
    gltron:
      "https://mega.nz/file/bkohEAoY#PeQFU3XfrLAwT-ioFlQlqvwkD_2G0-CjBrVUHGbT2ts",
  },
  {
    hacker:
      "https://mega.nz/file/PtAUTbQS#wqUeNPPTcjw2ZHcCSzAchP9_-NpFpDuElz0bMMwxdfo",
  },
  {
    happyLand:
      "https://mega.nz/file/qpA0gDAa#X7hK0JLumIsF3wfkKPRWo0aeCeCIrINt1hSYnOkvCOQ",
  },
  {
    lBreakoutTwo:
      "https://mega.nz/file/uww11IRC#ycKUnsxNVjaEaDVehW9Qo03XysOT2hp_Z-QMV4G0Drw",
  },
  {
    kaboom:
      "https://mega.nz/file/ewI0TD5S#aKWyEQDG9_H7wKLmN9Muged1XGzEJ10ZWKqXgVSEGac",
  },
  {
    mkWorm:
      "https://mega.nz/file/vlIWVbKA#odDU5AWM13rMDXFlVo2Db_1qudYjTGa2EGTS_wEHaWA",
  },
  {
    memory:
      "https://mega.nz/file/WlQmWR7C#5BTIaUsnNO8IH9g_GtZTAuaynDQGIVMGtCfKzGi0H24",
  },
  {
    pongSolo:
      "https://mega.nz/file/a4AGVJyA#K3bKEmw7AVXHnFaJV1W2rq4CtGZ18pv8kfqlaiVb5bI",
  },
  {
    plasticKitten:
      "https://mega.nz/file/G14mVJbQ#su4-sv0P27yQVQJu2z_Lf-dRRYQzCb6p4hdf611kBa8",
  },
  {
    stickSoldiers:
      "https://mega.nz/file/3o4UHAbT#n3bpjUOU8lA3VY1pcGuhKtWdSPsepAcpXzgdppZ6tMw",
  },
  {
    rcdScrabble:
      "https://mega.nz/file/mowkQCwa#kB6GQsJUB3Y_Sl5dfFmyN5pEDVeyh9J3uAFIDYVQx5g",
  },
  {
    ultimateSteroids:
      "https://mega.nz/file/K1wmkKYD#JDxjZK7SCABQNclZcgpL-K5Y8moxpsLQPd2eE4uU0b0",
  },
];

export { gameLinks };
export default gameLinks;
