const gameDescriptions = [
  { superMethaneBros: ["Super Methane Bros", "Platformer"] },
  { asteroidz3d: ["Asteroidz3D", "Shooter"] },
  { threeSixty: ["360", "Shooter"] },
  { threeDeeRacing: ["3D Racing", "Racing"] },
  { abaDaba: ["Aba Daba", "Puzzle"] },
  { codex: ["Codex", "Puzzle"] },
  { tetrisBreak: ["Tetris Break", "Puzzle"] },
  { yambo: ["Yambo", "Board Game"] },
  { powerShooter: ["Power Shooter", "Shooter"] },
  { houseOfUsher: ["House of Usher", "Platformer"] },
  { ufo: ["UFO", "Shooter"] },
  { marioXp: ["Mario XP", "Platformer"] },
  { madnessInteractive: ["Madness Interactive", "Shooter"] },
  { alex: ["Alex the Allegator 4", "Platformer"] },
  { absoluteMastermind: ["Absolute Mastermind", "Puzzle"] },
  { atoll: ["Atoll", "Puzzle"] },
  { atris: ["Alizarin Tetris", "Puzzle"] },
  { bricks: ["Bricks", "Block Breaker"] },
  { blackJack: ["BlackJack", "Card Game"] },
  { blocks: ["Blocks 2001", "Platformer"] },
  { camyTwo: ["Camy 2 - The Machine!", "Platformer"] },
  { capman: ["Capman", "Shooter"] },
  { chickenInvaders: ["Chicken Invaders", "Shooter"] },
  { colorMagic: ["Color Magic", "Puzzle"] },
  { cyberMind: ["CyberMind", "Puzzle"] },
  { cobjacks: ["Cobjacks", "Card Game"] },
  { crystalStacker: ["Crystal Stacker", "Puzzle"] },
  { dolphinDice: ["Dolphin Dice 2000", "Dice Game"] },
  { depthDiver: ["Depth Diver", "Action"] },
  { deluxePacman: ["Deluxe Pacman", "Maze Game"] },
  { drHorst: ["Dr Horst", "Puzzle"] },
  { dropsOfLight: ["Drops of Light", "Puzzle"] },
  { lordMonarchOnline: ["Lord Monarch Online", "Strategy"] },
  { darkWars: ["Dark Wars", "Shooter"] },
  { dxBall: ["DX-Ball", "Block Breaker"] },
  { driftZone: ["Driftzone", "Shooter"] },
  { egoboo: ["Egoboo", "RPG"] },
  { eyDice: ["Emperor Yang's Dice", "Dice Game"] },
  { factorX: ["Factor X", "Shooter"] },
  { frozenBubble: ["Frozen Bubble", "Puzzle"] },
  { frendz: ["Frendz", "Puzzle"] },
  { general: ["General", "Strategy"] },
  { gltron: ["GLTron", "Action"] },
  { hacker: ["Hacker", "Puzzle"] },
  { happyLand: ["Happyland Adventures", "Platformer"] },
  { lBreakoutTwo: ["LBreakout 2", "Block Breaker"] },
  { kaboom: ["KaBoom", "Card Game"] },
  { mkWorm: ["MK Worm", "Snake"] },
  { memory: ["Memory", "Memory Game"] },
  { pongSolo: ["Pong Solo", "Sports"] },
  { plasticKitten: ["Plastic Kitten", "Action"] },
  { stickSoldiers: ["Stick Soldiers", "Shooter"] },
  { rcdScrabble: ["RcdScrabble", "Board Game"] },
  { ultimateSteroids: ["Ultimate Steroids", "Board Game"] },
];

export { gameDescriptions };
export default gameDescriptions;
