import gameDescriptions from "../util/gameDescriptions";
import gameLinks from "../util/gameLinks";

const gameDetails = [
  "asteroidz3d",
  "threeSixty",
  "threeDeeRacing",
  "abaDaba",
  "codex",
  "tetrisBreak",
  "yambo",
  "powerShooter",
  "houseOfUsher",
  "ufo",
  "marioXp",
  "madnessInteractive",
  "alex",
  "absoluteMastermind",
  "atoll",
  "atris",
  "bricks",
  "blackJack",
  "blocks",
  "camyTwo",
  "capman",
  "chickenInvaders",
  "colorMagic",
  "cyberMind",
  "cobjacks",
  "crystalStacker",
  "dolphinDice",
  "depthDiver",
  "deluxePacman",
  "drHorst",
  "dropsOfLight",
  "lordMonarchOnline",
  "darkWars",
  "dxBall",
  "driftZone",
  "egoboo",
  "eyDice",
  "factorX",
  "frozenBubble",
  "frendz",
  "general",
  "gltron",
  "hacker",
  "happyLand",
  "lBreakoutTwo",
  "kaboom",
  "mkWorm",
  "memory",
  "pongSolo",
  "plasticKitten",
  "stickSoldiers",
  "rcdScrabble",
  "ultimateSteroids",
].map((item, index) => ({
  title: gameDescriptions[index][item][0],
  genre: gameDescriptions[index][item][1],
  image: item,
  gameLink: gameLinks[index][item],
}));

export { gameDetails };
export default gameDetails;
